export const MOEDAS = [
  { code: 'BRL', label: 'BRL — Real Brasileiro' },
  { code: 'USD', label: 'USD — Dólar Americano' },
  { code: 'EUR', label: 'EUR — Euro' },
  { code: 'GBP', label: 'GBP — Libra Esterlina' },
  { code: 'JPY', label: 'JPY — Iene Japonês' },
  { code: 'ARS', label: 'ARS — Peso Argentino' },
  { code: 'CLP', label: 'CLP — Peso Chileno' },
  { code: 'UYU', label: 'UYU — Peso Uruguaio' },
  { code: 'PYG', label: 'PYG — Guarani Paraguaio' },
  { code: 'COP', label: 'COP — Peso Colombiano' },
  { code: 'PEN', label: 'PEN — Sol Peruano' },
  { code: 'BOB', label: 'BOB — Boliviano' },
  { code: 'CAD', label: 'CAD — Dólar Canadense' },
  { code: 'AUD', label: 'AUD — Dólar Australiano' },
  { code: 'CHF', label: 'CHF — Franco Suíço' },
  { code: 'CNY', label: 'CNY — Yuan Chinês' },
  { code: 'MXN', label: 'MXN — Peso Mexicano' },
]
